hlo/models/attachment.py
import hashlib
import logging
from pathlib import Path

from django.contrib import admin
from django.core.cache import cache
from django.db import models
from django.urls import reverse
from django.utils.html import format_html

from hlo.utils.overwritingfilestorage import OverwritingFileSystemStorage

logger = logging.getLogger(__name__)


def attachment_file_path(instance, filename):
    if len(instance.sha1) != 40:  # noqa: PLR2004
        msg = f"SHA1 sum is not 40 chars: {instance.sha1}"
        raise ValueError(msg)
    suffix = Path(filename).suffix
    prefix = instance.sha1[:2]
    filename = instance.sha1[2:]
    return f"attachments/hashed/{prefix}/{filename}{suffix}"


class Attachment(models.Model):
    DEFAULT_ATTACHMENT_TYPE = "other"
    ATTACHMENT_TYPE_CHOICES = [
        ("datasheet", "Datasheet"),
        ("scrape", "Scraped page"),
        ("thumbnail", "Thumbnail"),
        ("other", "Other"),
    ]
    name = models.CharField(max_length=255, blank=True, default="")
    comment = models.CharField(max_length=255, blank=True, default="")
    type = models.CharField(
        max_length=50,
        choices=ATTACHMENT_TYPE_CHOICES,
        default=DEFAULT_ATTACHMENT_TYPE,
    )
    text = models.TextField(blank="", default="")

    # https://docs.djangoproject.com/en/3.2/ref/models/fields/#filefield
    file = models.FileField(
        upload_to=attachment_file_path,
        storage=OverwritingFileSystemStorage(),
        max_length=255,
        blank=True,
    )

    sha1 = models.CharField(max_length=40, editable=True)

    manual_input = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name} ({self.type}) ({Path(self.file.name).name})"

    def save(self, *args, **kwargs):
        # pylint: disable=no-member
        if self.file:
            with self.file.open("rb") as f:
                sha1hash = hashlib.sha1()  # noqa: S324
                if f.multiple_chunks():
                    for chunk in f.chunks():
                        sha1hash.update(chunk)
                else:
                    sha1hash.update(f.read())
                self.sha1 = sha1hash.hexdigest()
                logger.debug("Attachment SHA1 was %s", self.sha1)
                super().save(*args, **kwargs)
        else:
            self.sha1 = self.sha1 if self.sha1 else None
        super().save(*args, **kwargs)

    def clear_attachment_caches(self):
        """Update cache keys that depend on StockItems."""
        cache.delete_many(
            [
                "attachment_count",
                "attachment_pdf",
                "attachment_html",
            ],
        )

    def text_or_not(self):
        if len(self.text):
            return "There is text"
        return "There is no text"

    def file_name(self):
        if not self.file:
            return ""
        return Path(self.file.name).name

    def get_parent(self):
        # pylint: disable=no-member
        if self.order.count():
            return self.order.first()
        return self.orderitem.first()

    @admin.display(description="Manual input")
    def text_manual_input(self) -> str:
        return "Yes" if self.manual_input else "No"

    def used_by(self):
        # pylint: disable=no-member
        if self.order.count():
            order = self.order.first()
            return format_html(
                '<a href="{}">{} ({})</a>',
                reverse(
                    "admin:hlo_order_change",
                    args=(order.id,),
                ),
                order.order_id,
                order.shop.branch_name,
            )
        orderitem = self.orderitem.first()
        return format_html(
            '<a href="{}">{}</a>',
            reverse(
                "admin:hlo_orderitem_change",
                args=(orderitem.id,),
            ),
            orderitem.name,
        )

hlo/models/orderitem.py
from __future__ import annotations

import hashlib
import logging
import pprint
from io import BytesIO
from pathlib import Path
from typing import TYPE_CHECKING

from django.contrib import admin
from django.core.cache import cache
from django.core.files.images import ImageFile
from django.db import models
from django.db.models import Case, F, When
from django.urls import reverse
from django.utils.html import escape, format_html
from django.utils.safestring import mark_safe
from djmoney.models.fields import MoneyField

from hlo.utils.overwritingfilestorage import OverwritingFileSystemStorage

from . import Attachment, Order

if TYPE_CHECKING:
    from django.utils.safestring import SafeString

logger = logging.getLogger(__name__)


def thumbnail_path(instance: OrderItem, filename: str) -> str:
    if len(instance.thumbnail_sha1) != 40:  # noqa: PLR2004
        msg = f"SHA1 sum is not 40 chars: {instance.thumbnail_sha1}"
        raise ValueError(msg)
    suffix = Path(filename).suffix
    prefix = instance.thumbnail_sha1[:2]
    filename = instance.thumbnail_sha1[2:]
    return f"thumbnails/hashed/{prefix}/{filename}{suffix}"


class OrderItem(models.Model):  # type: ignore[django-manager-missing]
    # the class declaration line in a class that is the target of a ForeignKey
    # from a model with untyped / dynamically added managers as it happens
    # on the reverse relation
    name = models.CharField(max_length=255)
    item_id = models.CharField(
        "Shop item ID",
        max_length=100,
        default="",
        help_text=(
            "The original item id from the shop. Not to be "
            "confused with the internal database id."
        ),
        blank=False,
    )
    item_variation = models.CharField(
        "Item SKU/variation",
        max_length=255,
        default="",
        help_text="The original item sku.",
        blank=True,
    )
    count = models.PositiveIntegerField("number of items", default=1)
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name="items",
    )
    total = MoneyField(
        "Item price",
        max_digits=19,
        decimal_places=4,
        default_currency=None,
        blank=True,
        null=True,
    )  # type: ignore[reportCallIssue]

    total_nok = models.GeneratedField(
        expression=Case(
            When(total_currency="JPY", then=F("total") * 0.0716),
            When(total_currency="USD", then=F("total") * 11.10),
            When(total_currency="GBP", then=F("total") * 14.02),
            When(total_currency="EUR", then=F("total") * 11.72),
            default=F("total"),
            output_field=models.DecimalField(max_digits=19, decimal_places=4),
        ),
        db_persist=False,
        output_field=models.DecimalField(max_digits=19, decimal_places=4),
    )

    subtotal = MoneyField(
        "Item subtotal",
        max_digits=19,
        decimal_places=4,
        default_currency=None,
        blank=True,
        null=True,
    )  # type: ignore[reportCallIssue]
    tax = MoneyField(
        "Item tax/vat",
        max_digits=19,
        decimal_places=4,
        default_currency=None,
        blank=True,
        null=True,
    )  # type: ignore[reportCallIssue]
    attachments = models.ManyToManyField(
        Attachment,
        related_name="orderitem",
        blank=True,
    )

    thumbnail = models.ImageField(
        upload_to=thumbnail_path,  # type: ignore[reportArgumentType]
        storage=OverwritingFileSystemStorage(),
        blank=True,
    )
    # Extra data that we do not import into model
    extra_data = models.JSONField(default=dict, blank=True)

    thumbnail_sha1 = models.CharField(
        max_length=40,
        editable=False,
        default="",
        blank=True,
    )
    # Weak, *static* FK for StockItem
    sha1_id = models.CharField(
        max_length=40,
        unique=True,
    )

    manual_input = models.BooleanField(default=True)

    class Meta:
        ordering = ["order__date", "name"]
        constraints = [
            models.UniqueConstraint(
                fields=["item_id", "item_variation", "order"],
                name="unique_id_sku_order",
            ),
        ]

    def __str__(self) -> str:
        """Return string representation.

        Includes shop, order and item id, variation and NameError
        """
        return (
            # pylint: disable=no-member
            f"{self.pk}: {self.order.shop.branch_name} "
            f" #{self.order.order_id}#{self.item_id}"
            f"/{self.item_variation if len(self.item_variation) else ''}"
            f": {self.name}"
        )

    def save(self, *args, **kwargs) -> None:
        self.thumbnail_sha1 = ""

        buf = BytesIO()
        if self.thumbnail:
            with self.thumbnail.open("rb") as f:
                thumbnail_hash = hashlib.sha1()  # noqa: S324
                if f.multiple_chunks():
                    for chunk in f.chunks():
                        thumbnail_hash.update(chunk)
                        buf.write(chunk)
                else:
                    data = f.read()
                    thumbnail_hash.update(data)
                    buf.write(data)
                self.thumbnail_sha1 = thumbnail_hash.hexdigest()
            buffer_file = ImageFile(buf)
            self.thumbnail.file = buffer_file

        item_variation = "novariation"
        if len(self.item_variation):
            item_variation = self.item_variation

        orderitem_hash = hashlib.sha1()  # noqa: S324
        orderitem_hash.update(
            (
                f"{self.order.shop.branch_name}-{self.order.order_id}-"
                f"{self.item_id}-{item_variation}"
            ).encode(),  # defaults to utf-8
        )
        self.sha1_id = orderitem_hash.hexdigest().upper()
        super().save(*args, **kwargs)
        self.clear_orderitem_caches()

    def get_absolute_url(self) -> str:
        return reverse("orderitem-detail", kwargs={"pk": self.pk})

    def clear_orderitem_caches(self):
        """Update cache keys that depend on StockItems."""
        cache.delete_many(
            [
                "orderitem_raw_count",
                "orderitem_unprocessed_count",
                "orderitem_processed_count",
                "stockitem_count",
            ],
        )

    def simple_image_tag(
        self,
        max_width: int = 300,
        max_height: int = 300,
        classes=None,
        style="",
    ) -> SafeString:
        if classes is None:
            classes = []
        return mark_safe(  # noqa: S308
            f'<img src="{self.thumbnail.url}" class="{" ".join(classes)}" '
            f'style="max-height: {max_height}px; '
            f'max-width: {max_width}px; {style}"/>',
        )

    @admin.display(description="Preview")
    def admin_image_tag(self) -> SafeString:
        return self.simple_image_tag(300, 300)

    def image_tag(self, px: int = 150, max_width: int = 0) -> SafeString:
        # pylint: disable=no-member
        max_width = (
            min(self.thumbnail.width, max_width)
            if max_width
            else self.thumbnail.width
        )
        if px:
            return mark_safe(  # noqa: S308
                f'<div style="height: {px}px;"><a href="{self.thumbnail.url}"'
                ' target="_blank"><img style="height: auto; width: auto;"'
                f' src="{self.thumbnail.url}" width="{self.thumbnail.width}"'
                f' height="{self.thumbnail.height}" /></a></div>',
            )
        return mark_safe(  # noqa: S308
            f'<img style="max-height: 100%; '
            f'width: { f"{max_width} px" if max_width else "auto" };"'
            f' src="{self.thumbnail.url}" />',
        )

    @admin.display(description="Attachments")
    def attachments_tag(self) -> SafeString | str:
        # pylint: disable=no-member
        if self.attachments.count() == 0:
            return "No attachments"
        html = '<ul style="margin: 0;">'
        for attachment in self.attachments.all():
            html += (
                f'<li><a href="{attachment.file.url}"'
                f' target="_blank">{attachment}</a></li>'
            )
        html += "</ul>"
        return mark_safe(html)  # noqa: S308

    @admin.display(description="Item ID / SKU")
    def item_ref(self) -> str:
        return (
            f"{self.item_id}"
            f"{' / ' if len(self.item_variation) else ''}"
            f"{self.item_variation}"
        )

    @admin.display(description="Manual input")
    def text_manual_input(self) -> str:
        return "Yes" if self.manual_input else "No"

    def get_orderitem_url(self) -> str:
        return self.order.shop.item_url_template.format(item_id=self.item_id)

    @admin.display(description="Order ID")
    def item_url(self) -> SafeString:
        return format_html(
            '{} (<a href="{}" target="_blank">Open item page on {}}</a>)',
            self.order_id,  # type: ignore[reportAttributeAccessIssue]
            # pylint: disable=no-member
            self.shop.order_url_template.format(order_id=self.order_id),  # type: ignore[reportAttributeAccessIssue,attr-defined]
            self.shop.branch_name,  # type: ignore[reportAttributeAccessIssue,attr-defined]
        )

    @admin.display(description="Extra data (indented)")
    def indent_extra_data(self) -> SafeString:
        return format_html(
            "<pre>{}</pre>",
            escape(pprint.PrettyPrinter(indent=2).pformat(self.extra_data)),
        )


class OrderItemMeta(models.Model):
    parent = models.OneToOneField(
        OrderItem,
        to_field="sha1_id",
        on_delete=models.DO_NOTHING,
        db_constraint=False,
        related_name="meta",
    )
    hidden = models.BooleanField(default=False)
    label_printed = models.BooleanField(default=False)
    comment = models.CharField(max_length=255, default="", blank=True)

hlo/forms/__init__.py
from .attachment import (
    AttachmentForm,
    AttachmentFormSet,
    AttachmentFormSetHelper,
)
from .order import OrderForm, OrderFormSimple
from .orderitem import OrderItemForm
from .shop import ShopForm
from .stockitem import StockItemForm

__all__ = [
    "StockItemForm",
    "OrderForm",
    "OrderFormSimple",
    "ShopForm",
    "OrderItemForm",
    "AttachmentForm",
    "AttachmentFormSet",
    "AttachmentFormSetHelper",
]

hlo/forms/attachment.py
import logging

from crispy_forms.helper import FormHelper  # type: ignore[import-untyped]
from crispy_forms.layout import (  # type: ignore[import-untyped]
    Column,
    Field,
    Row,
)
from django.forms import ModelForm, modelformset_factory

from hlo.models import Attachment

logger = logging.getLogger(__name__)


class AttachmentForm(ModelForm):
    class Meta:
        model = Attachment
        exclude = ["comment", "text", "manual_input", "sha1"]  # noqa: DJ006


AttachmentFormSet = modelformset_factory(
    model=Attachment,
    form=AttachmentForm,
    extra=1,
)


class AttachmentFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_method = "POST"
        self.form_class = "form-vertical"
        self.label_class = "col"
        self.field_class = "col"
        self.render_required_fields = True
        self.form_tag = False
        self.add_layout(
            Column(
                Row(
                    Column(Field("name")),
                    Column(
                        Field("type"),
                    ),
                    Column(Field("file")),
                ),
            ),
        )

hlo/admin/__init__.py
import logging

from django.contrib import admin
from django.contrib.auth.admin import UserAdmin

from hlo.models import User

from .attachment import AttachmentAdmin
from .commontree import CategoryAdmin, ProjectAdmin, StorageAdmin
from .order import OrderAdmin
from .orderitem import (
    OrderItemAdmin,
    OrderItemMetaAdmin,
    OrderStockItemLinkAdmin,
)
from .shop import ShopAdmin
from .stockitem import StockItemAdmin

logger = logging.getLogger(__name__)

__all__ = [
    "AttachmentAdmin",
    "CategoryAdmin",
    "CategoryResource",
    "OrderAdmin",
    "OrderItemAdmin",
    "OrderItemMetaAdmin",
    "OrderStockItemLinkAdmin",
    "ProjectAdmin",
    "ShopAdmin",
    "StockItemAdmin",
    "StorageAdmin",
    "User",
]

admin.site.register(User, UserAdmin)

hlo/admin/commontree/__init__.py
from .category import CategoryAdmin
from .project import ProjectAdmin
from .storage import StorageAdmin

__all__ = [
    "CategoryAdmin",
    "ProjectAdmin",
    "StorageAdmin",
]

hlo/filters/__init__.py
__all__ = [
    "OrderItemFilter",
    "StockItemFilter",
    "NonOrderingOrderItemFilter",
    "NonOrderingStockItemFilter",
    "OrderDateRangeFilter",
]
from .orderdaterangefilter import OrderDateRangeFilter
from .orderitemfilter import NonOrderingOrderItemFilter, OrderItemFilter
from .stockitemfilter import NonOrderingStockItemFilter, StockItemFilter

hlo/management/commands/loaders/__init__.py
from .shopmetaloader import ShopMetaLoader
from .shoporderloader import ShopOrderLoader

__all__ = [
    "ShopMetaLoader",
    "ShopOrderLoader",
]

hlo/models/commontree/__init__.py
__all__ = [
    "Category",
    "CommonTreeModel",
    "Project",
    "Storage",
]
from .category import Category
from .commontree import CommonTreeModel
from .project import Project
from .storage import Storage

hlo/templates/stockitem/detail.html
{% extends "common/base.html" %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}
{% load mptt_tags %}
{% block title %}
  Details for {{ stock_item.name }}
{% endblock title %}
{% block head %}
  <script type="text/javascript">
    var print_urls = {
      {% for num in range %}{{ num }}: "{% url 'label-print-sha1-size' stockitem.sha1_id num %}",
      {% endfor %}
    };
    var render_urls = {
      {% for num in range %}{{ num }}: "{% url 'label-render-sha1-size' stockitem.sha1_id num %}",
      {% endfor %}
    };
    
    async function printLabelWithSize(size) {
      let url = print_urls[size]
      console.log("Printing with size, url", size, url)
      try {
        const response = await fetch(url, {
          method: "POST",
          headers: {
            'X-CSRFToken': window.csrftoken,
          },
        });
        if (!response.ok) {
          const json = await response.json();
          alert(json["reason"] + ": " + json["text"] )
        } else {
          document.querySelector('#print-label').innerHTML = "Reprint label";
        }
      } catch (error) {
        alert(`Serverside error: ${error.message}`)
        console.error(error.message);
      }
    }
    

    window.addEventListener("load", () => { 
      window.csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
      console.log("CSRF token", csrftoken)
      document.querySelector('#print-label').addEventListener("click", (event) => {
        if ({{ stockitem.label_printed | yesno:"true,false" }}) {
          if (confirm("A label for this item has already been printed.\n\nAre you sure you want to print a new label?") != true) {
              return
          }
        }
        printLabelWithSize(document.querySelector("#print_multiplier").value)
      });

      document.querySelector('#print_multiplier').addEventListener("change", (event) => {
        document.querySelector('#label_img').onload = function (){
          window.scrollTo(0, document.body.scrollHeight); /* large images */
        };
        document.querySelector('#label_img').src = render_urls[event.target.value];
      });
    });
  </script>
{% endblock head %}
{% block content %}
  <div class="row mt-3">
    <div class="col-12 col-lg-7 col-xl-7 col-xxl-7">
      <div class="row">
        <!-- title -->
        <div class="col-12">
          <h3>
            {{ stockitem }}
            {% if stockitem.count != 1 or stockitem.count_unit != "items" %}
              <span class="text-secondary">({{ stockitem.count }} {{ stockitem.count_unit }})</span>
            {% endif %}
            <a class="btn btn-outline-secondary btn-sm"
               href="{% url 'stockitem-update' stockitem.id %}"
               role="button">Edit</a>
            {% if request.user.is_staff %}
              <a class="btn btn-outline-secondary btn-sm"
                 href="{% url 'admin:hlo_stockitem_change' stockitem.id %}"
                 role="button" target="_blank">Open admin view</a>
            {% endif %}
          </h3>
        </div>
      </div>
      <div class="row d-lg-none d-xl-none d-xxl-none">
        <!-- small screen image -->
        <div class="col">
          <!-- Render image on top for <  lg -->
          {% for orderitem in stockitem.orderitems.all %}
            {# djlint:off #}
            <img alt="Item thumbnail" src="{{ stockitem.thumbnail_url }}" class="img-fluid" />
            {# djlint:on #}
          {% empty %}
            <!-- No missing image for small screens -->
          {% endfor %}
        </div>
      </div>
      <div class="row mt-3">
        <!-- table -->
        <div class="col-12">
          <div class="table-responsive">
            <table class="table">
              <tr class="table-dark">
                <td>Tags</td>
                <td>
                  {% for tag in stockitem.tags.all %}
                    <span class="badge text-bg-dark rounded-pill pe-2">{{ tag.name }}</span>
                  {% endfor %}
                </td>
              </tr>
              <tr>
                <td>Categories</td>
                <td colspan="2">
                  <ul class="list">
                    {% for tag in stockitem.category.all %}
                      <li class="list-item">{{ tag.name }}</li>
                    {% empty %}
                      <li class="list-item">No categories</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
              <tr>
                <td>Projects</td>
                <td colspan="2">
                  <ul class="list">
                    {% for tag in stockitem.project.all %}
                      <li class="list-item">{{ tag.name }}</li>
                    {% empty %}
                      <li class="list-item">No projects</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
              <tr>
                <td>Storage</td>
                <td colspan="2">
                  <ul class="list">
                    {% for storage in stockitem.storage.all %}
                      <li class="list-item">
                        <a href="{% url "storage-detail" storage.pk %}">
                          {% if storage.get_ancestors|length %}{{ storage.get_ancestors|tree_path:" > " }} >{% endif %}
                        {{ storage }}</a>
                      </li>
                    {% empty %}
                      <li class="list-item">No storage locations</li>
                    {% endfor %}
                  </ul>
                </td>
              </tr>
              {% if stockitem.comment %}
              <tr><td>Comment</td><td>{{ stockitem.comment }}</td></tr>
              {% endif %}
              <tr class="table-dark">
                <td colspan="2">Related items and attachments</td>
              </tr>
              <tr>
                <td class="table-secondary">Order items</td>
                <td>
                  {% for orderitem in stockitem.orderitems.all %}
                    <a href="{% url "orderitem-detail" orderitem.pk %}">{{ orderitem }} ({{ orderitem.pk }})</a>
                    <br>
                    {% if orderitem.attachments.all %}<ul>{% endif %}
                      {% for attachment in orderitem.attachments.all %}
                        <li>
                          <a href="{{ attachment.file.url }}" target="_blank">{{ attachment.name }}</a>
                        </li>
                      {% endfor %}
                      {% if orderitem.attachments.all %}</ul>{% endif %}
                  {% empty %}
                    No linked order items
                  {% endfor %}
                </td>
              </tr>
              <tr>
                <td class="table-secondary">Attachments</td>
                <td>
                  {% for attachment in stockitem.attachments.all %}
                    {{ attachment }}
                    <br>
                  {% empty %}
                    No attachments
                  {% endfor %}
                </td>
              </tr>
              <tr class="d-none d-sm-none d-md-none d-lg-table-row d-xl-table-row d-xxl-table-row">
                <td class="table-secondary">Label</td>
                <td>
                  <p>
                    <img src="{% url 'label-render-sha1-size' stockitem.sha1_id 4 %}"
                         width="400"
                         id="label_img" />
                  </p>

                    <div class="input-group mb-3">
                      <select class="form-control" id="print_multiplier" name="print_multiplier" style="flex: unset; width: auto;">
                        <option value="1">55mm (QR)</option>
                        <option value="2">27.4mm (QR)</option>
                        <option value="3">18.5mm (QR))</option>
                        <option value="4" selected>Stock (13.7mm)</option>
                        <option value="5">10.8 mm</option>
                        <option value="6">8.9 mm</option>
                        <option value="7">7.7 mm</option>
                        <option value="8">6.8 mm</option>
                        <option value="9">5.7 mm (MicroSD)</option>
                        <option value="10">5.4 mm</option>
                        <option value="11">4.7 mm</option>
                        <option value="12">4.4 mm</option>
                      </select>
                        <a id="print-label" class="btn btn-primary">
                          {% if stockitem.label_printed %}
                            Reprint label
                          {% else %}
                            Print label
                          {% endif %}
                        </a>
                    </div>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
    <div class="col-5 d-none d-lg-block d-xl-block d-xxl-block">
      <!-- Render image to the side for >= lg -->
      {% if stockitem.thumbnail_url %}
        <img alt="Image thumbnail"
             src="{{ stockitem.thumbnail_url }}"
             class="img-fluid"
             style="max-width: 90%" />
      {% else %}
        {% md_icon 'image-off' color='grey' size='10em' %}
      {% endif %}
    </div>
  </div>
  {% csrf_token %}
{% endblock content %}

hlo/templates/stockitem/form.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap_icons %}
{% load widget_tweaks %}
{% load static %}
{% block title %}
    {{ title }}
{% endblock title %}
{% block head %}
    <link rel="stylesheet" href="{% static 'select2-bootstrap-5-theme/select2-bootstrap-5-theme.css' %}" />
 
    <link rel="stylesheet"
          href="{% static 'js/multiselect-dropdown/multiselect-dropdown.css' %}">
    <script src="{% static 'js/select-drop-paste.js' %}"></script>
    <script type="text/javascript">
        new SDP({
            showErrorCallback: showError,
            hideErrorCallback: hideError,
            fileInputElement: "#id_thumbnail",
            dropzoneElement: "#dropzone",
            acceptedMimeTypes: ['image/png', 'image/jpeg'],
            debug: false,
            newFileCallback: previewFile
        });
        function showError(msg) {

        }
        function hideError() {

        }
        function previewFile(file) {
            const preview = document.querySelector("#thumbnail");
            preview.classList.remove("d-none");
            const reader = new FileReader();
            reader.addEventListener("load", () => {
                preview.src = reader.result;
            }, false);
            reader.readAsDataURL(file);
        }

        window.addEventListener("load", () => {
            document.querySelector("#id_thumbnail_btnclear").addEventListener(
                'click', 
                () => { 
                    document.querySelector('#id_thumbnail').value=null;
                    const preview = document.querySelector("#thumbnail");
                    const original_url = "{% if stockitem.thumbnail_url %}{{ stockitem.thumbnail_url }}{% elif orderitem.thumbnail %}{{ orderitem.thumbnail.url }}{% endif %}";
                    if (original_url) {
                        preview.src = original_url;
                    } else {
                        preview.classList.add("d-none");
                    }
                    
                }
                );
            
            $("#btn_diameter").on("click", function() { 
                $("#id_name").get(0).setRangeText("⌀")
            })
            $("#btn_degree").on("click", function() { 
                $("#id_name").get(0).setRangeText("°")
            })
            $("#unit_btn").on("click", function() { 
                var v = prompt("New unit")
                if (v.length > 0) {
                    $("#id_count_unit").append(new Option(v,v));
                    $("#id_count_unit").val(v).change();
                }
            })
        });
    </script>
    <link href="{% static 'css/select2-bootstrap5-dark.css' %}" media="screen" rel="stylesheet">
{% endblock head %}
{% block css %}

{% endblock css %}
{% block modals %}
    <div class="modal" tabindex="-1" id="keyboardModel">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button"
                            class="btn btn-primary"
                            id="btn_diameter"
                            data-bs-dismiss="modal">⌀</button>
                    <button type="button"
                            class="btn btn-primary"
                            id="btn_degree"
                            data-bs-dismiss="modal">°</button>
                </div>
            </div>
        </div>
    </div>
{% endblock modals %}
{% block content %}
    <div class="row mt-2 mb-4">
        <div class="col-6">
            {% if stockitem.name %}
                <h1>{{ stockitem.name }}</h1>
            {% else %}
                <h1>
                    Create stock item
                    <br>
                </h1>
                <h4 class="text-secondary">{{ original_name }}</h4>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-9">{% crispy form %}</div>
        <div class="col-3 ">
            TODO: Rotate buttons
            {% if stockitem.thumbnail_url %}
                <img alt="Image thumbnail"
                     src="{{ stockitem.thumbnail_url }}"
                     class="img-fluid"
                     style="max-width: 90%" id="thumbnail" />
            {% elif orderitem.thumbnail %}
                <img alt="Image thumbnail"
                     src="{{ orderitem.thumbnail.url }}"
                     class="img-fluid"
                     style="max-width: 90%" id="thumbnail" />
            {% else %}
                {% md_icon 'image-off' color='grey' size="10em" %}
            {% endif %}
        </div>
    </div>
    {% endblock content %}
    {% block bodybottom %}
        <script type="text/javascript">

        </script>
        <!-- Used for storage/project/category -->
       <!--  <script src="{% static 'js/multiselect-dropdown/multiselect-dropdown.js' %}"></script> -->
        <link rel="stylesheet" href="" media="screen" />

    {% endblock bodybottom %}